### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by marianopaulin02** [Geodan/concave-hull#2]
Hi, this is a very useful tool. I'd like to know if this python wrapper represents an advantage in front of use the command line implementation. I mean, the command line requires store the points in files and with this tool I can pass points just with python arrays. I couldn't  find how this connection is made in the source code. Can you explain a bit more of it?

**Comment by chrislcs** [comment]
The connection is made using pybind11, which adds a `py::array_t` type to C++. The `ReadInput` function then converts the `py:array_t` to `std::vector<Point>`, which is then used as input in the original code, as provided in [the article](https://www.codeproject.com/Articles/1201438/The-Concave-Hull-of-a-Set-of-Points). The data is never saved to disk, only in memory, so depending on your use case this could definitely give a performance increase.

**Comment by marianopaulin02** [comment]
Thank you for the reply. It's what I was looking for.
