### ISSUE TITLE
Trouble installing the concave hull pakage

### ISSUE THREAD

**Issue by smusman** [Geodan/concave-hull#3]
I'm having trouble installing the concave hull package. Can you kindly elaborate the installation process on windows.

**Comment by smusman** [comment]
`C:\Users\usman\Desktop\concave-hull-master\concave-hull-master>pip install .
Processing c:\users\usman\desktop\concave-hull-master\concave-hull-master
Requirement already satisfied: pybind11>=2.2 in c:\users\usman\appdata\local\programs\python\python37-32\lib\site-packages (from concave-hull==1.0.0) (2.2.4)
Installing collected packages: concave-hull
  Running setup.py install for concave-hull ... error
    ERROR: Complete output from command 'c:\users\usman\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\usman\\AppData\\Local\\Temp\\pip-req-build-4gnpjegs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\usman\AppData\Local\Temp\pip-record-z1947tzu\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'concave_hull' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\users\usman\appdata\local\programs\python\python37-32\Include -IC:\Users\usman\AppData\Roaming\Python\Python37\Include -Ipath/to/flann/dir\include -Ic:\users\usman\appdata\local\programs\python\python37-32\include -Ic:\users\usman\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpsrc/main.cpp /Fobuild\temp.win32-3.7\Release\src/main.obj /EHsc /DVERSION_INFO=\"1.0.0\"
    main.cpp
    src/main.cpp(15): fatal error C1083: Cannot open include file: 'flann/flann.hpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\users\usman\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\usman\\AppData\\Local\\Temp\\pip-req-build-4gnpjegs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\usman\AppData\Local\Temp\pip-record-z1947tzu\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\usman\AppData\Local\Temp\pip-req-build-4gnpjegs\
`
This is my error

**Comment by chrislcs** [comment]
> Cannot open include file: 'flann/flann.hpp': No such file or directory error: command

Seems flann is not installed correctly or not set in the environment variables. Before doing `pip install .` make sure you set the flann directory in the environment variables either via the control panel or via the command `set FLANN_DIR=path/to/flann/dir` (note that using the `set` command only sets the variable for that session in the command prompt.)

**Comment by smusman** [comment]
Got it done on Ubuntu. Still no clue why I wasn't able to do it on windows.
